### ISSUE TITLE
Github Configuration

### ISSUE THREAD

**Issue by SleepyBulldozer** [SleepyBulldozer/munchkin-net#1]
### Description
Github comes with a number of default configurations that are very broad.  This task will update the configuration of the Github project to be suitable for development.

### Tasks
- [x] Create ISSUE_TEMPLATES
- [x] Create initial milestones (Assign this issue to it)
- [x] Create project label schema
- [ ] Update initial README file to contain some initial information
